"""Initial migration

Revision ID: 6e74309131f7
Revises: 
Create Date: 2025-05-23 13:26:10.095863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e74309131f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_job_client_id', 'client', ['client_id'], ['id'])
        batch_op.drop_column('client_name')
        batch_op.drop_column('client_email')
        batch_op.drop_column('client_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('client_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('client_name', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('fk_job_client_id', type_='foreignkey')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
